### ISSUE TITLE
Players not getting the resourcepack prompt

### ISSUE THREAD

**Issue by MicleBrick** [Phoenix616/ResourcepacksPlugins#22]
/usepack says they already have the pack, but it never sends it to them. Version: 1.6.19-SNAPSHOT (build 249)

## Config

```
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  slpack:
    url: https://github.com/StarLegacy/StarLegacyResourcepack/releases/download/v3.0/StarLegacyResourcepack.v3.0.zip
    hash: 8a35431fc44baacf3162ab0f2ab620a4ba251826
empty: slpack
global:
  send-delay: 20
  pack: slpack
servers:
  survival:
    pack: slpack
    send-delay: 20
  creative:
    pack: slpack
    send-delay: 20
```

**Comment by Phoenix616** [comment]
I'm assuming that you are trying to set the slpack pack as it's the only one in your config? If so then the issue is that you defined the pack as the empty one. If you do that the plugin will treat people without a pack the same as if they had that pack applied. So they already have the empty pack (none) in your case.

I highly recommend using the default empty pack (as it's really empty) which would solve your issue. (You have the pack applied to all servers anyways with the global option, your per-server packs won't even do anything)

This behaviour is one of the main reasons of why I changed the configuration from just defining the name of a pack at the empty-node [to the full pack definition](https://github.com/Phoenix616/ResourcepacksPlugins/blob/master/bungee/src/main/resources/bungee-config.yml#L37-L40) to make it harder to accidentally end up in a situation like yours.

**Comment by Miclebrick** [comment]
So, this should work?:
```
debug: true
autogeneratehashes: true
messages:
  usepack: You now use the pack %pack%!
  packlisthead: 'Packs available to you:'
  nopacks: No packs found!
packs:
  slpack:
    url: https://github.com/StarLegacy/StarLegacyResourcepack/releases/download/v3.0/StarLegacyResourcepack.v3.0.zip
    hash: 8a35431fc44baacf3162ab0f2ab620a4ba251826
empty: slpack
global:
  send-delay: 20
```

**Comment by Miclebrick** [comment]
nevermind, I get it now. I'll try that.

**Comment by Phoenix616** [comment]
No, it wont send the empty pack if the player doesn't have a server pack applied. Just leave the empty pack like the default config and set your pack like previously as the global pack.
